--
-- Up
--
CREATE TABLE "users" ( `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, `identifiant` TEXT NOT NULL UNIQUE, `voices` INTEGER NOT NULL DEFAULT 1, `team` INTEGER NOT NULL, `voted` INTEGER DEFAULT 0 );
CREATE TABLE "teams" ( `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `team_name` TEXT NOT NULL UNIQUE );
CREATE TABLE `results` ( `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `userid` TEXT NOT NULL, `teamvoted` INTEGER NOT NULL );


--
-- Down
--